### ISSUE TITLE
kanboard setup

### ISSUE THREAD

**Issue by mugishasam123** [mugishasam123/Space-hub#25]
## project setup

- we are two working on this project 
-  @mugishasam123 and @joskalenda 

- link to the [project ](https://github.com/mugishasam123/Space-hub/projects/1)

**Comment by Mihndim2020** [comment]
# STATUS: INVALID!!!  :x: :x: :x: 

Hi Team,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code, please make sure your implement the following changes before you resubmit for review. 

## Required Changes ♻️
_Check the comments below._
- [ ] Please kindly submit a link  to the `GitHub project` in the issue as it is a requirement for this project.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by rustam-tolipov** [comment]
## HELLO @joskalenda  and @mugishasam123 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 🎉 🎉 🎉 🎉, 

Cheers and Happy coding!👏👏👏

![Developer-512px-10](https://user-images.githubusercontent.com/69011963/151541305-67f4f8e4-c79e-4f9d-a6cf-2c7efc3102c6.gif)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```
